### PR TITLE
smartos-ui#9 build_stamp definition should pass cargo check

### LINKED ISSUE #9: build_stamp definition should pass `cargo check`.
In order to have a consistent build stamp, we generate one in the Makefile and do a compile-time import of the env var. This causes `cargo check` to throw an error:

```
] cargo check
   Compiling smartos_ui v0.1.20 (/Users/bahamat/src/joyent/smartos-ui/ui)
error: STAMP not defined.
  --> ui/src/main.rs:34:23
   |
34 |     let build_stamp = env!("STAMP", "STAMP not defined.");
   |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: this error originates in the macro `env` (in Nightly builds, run with -Z macro-backtrace for more info)

error: could not compile `smartos_ui` (bin "smartos_ui") due to previous error
```

We want to be able to `cargo check` without having to explicitly define the variable. Among other things, this helps with using IDEs that aren't going to set it.

### PR DESCRIPTION
**Pull request by bahamat**
This was bugging me for a bit, and I figured out how to fix it today. Fixes #9.

### CODE REVIEW

**Review by danmcd — APPROVED** [review]

**Review by danmcd — CHANGES_REQUESTED** [review]
Shoot, spoke too soon.  Jenkins has some concerns, it seems.

**Comment by bahamat** [comment]
Output from most recent build:

```
[root@smartos-pb ~]# uiadm info
Version: 0.1.20-3d49523 master-20240823T161538Z-g3d49523
URL: https://192.168.122.184:4443
```

Note the git-describe of `g3d49523` matches the current commit of `3d49523`. So we're definitely getting exactly what we expect here.

**Review by danmcd — APPROVED** [review]
Brilliant.  I suspect the transitive closure (transitive reduction, turns out) might have loops, and if it does that's NP-hard.

**Review by teutat3s — APPROVED** [review]

**Comment by bahamat** [comment]
> Brilliant. I suspect the transitive closure (transitive reduction, turns out) might have loops, and if it does that's NP-hard.

Maybe, but this is at least a compile-time thing. The `optional_env!().unwrap_or()` will compile down to a static string in the resulting binary, so it has no runtime impact either way.

**Pull request merged**
